name: pattern-lab
recipe: drupal8

config:
  webroot: .
  drush: global:8.1.16

services:
  database:
    type: mysql:5.7
  node:
    type: node:8
    globals:
      gulp-cli: "latest"

tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
