services:
  apache:
    image: tugboatqa/httpd:2.4
    default: true
  node:
    image: tugboatqa/node:latest
  php:
    image: tugboatqa/php:7.3-apache

commands:
      init:
        - npm install gulp
        - ./patternlab-install.sh
        - ./patternlab-provision.sh
        - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
      update:
        - gulp patternlab
      build:
        - gulp patternlab
        - php pattern-lab/core/console --generate
        - php pattern-lab/core/console --server --port 8000
