services:
  apache:
    image: tugboatqa/httpd:2.4
    default: true
    commands:
          init:
            - curl -sL https://deb.nodesource.com/setup_8.x| sudo -E bash -
            - apt-get install -y nodejs
            - apt-get install -y npm
            - apt-get install -y gcc g++ make
            - npm -g install gulp
            - apt-get install -y curl php-cli php-mbstring git unzip
            - apt-get install bsdtar -y
            - curl -sS https://getcomposer.org/installer -o composer-setup.php
            - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            - composer create-project -n pattern-lab/edition-twig-standard pattern-lab
            - cd pattern-lab
            - composer require aleksip/plugin-data-transform
            - cd ../
            - php pattern-lab/core/console -c --set sourceDir=../source
            - php pattern-lab/core/console -c --set twigAutoescape=0
            - php pattern-lab/core/console --generate
            - ln -snf "${TUGBOAT_ROOT}/pattern-lab/public" "${DOCROOT}"
