services:
  apache:
    image: tugboatqa/httpd:2.4
    default: true
    commands:
          init:
            - curl -sL https://deb.nodesource.com/setup_8.x| sudo -E bash -
            - apt-get install -y nodejs
            - apt-get install -y npm
            - apt-get install -y gcc g++ make
            - npm install gulp
            - ./patternlab-install.sh
            - ./patternlab-provision.sh
            - apt-get install php
            - php pattern-lab/core/console --generate
            - ln -snf "${TUGBOAT_ROOT}/pattern-lab/public" "${DOCROOT}"
          update:
            - gulp patternlab
          build:
            - gulp patternlab
            - php pattern-lab/core/console --generate
